data_source:
  path: "data"
dataset:
  name: "raw"
dataset_specific:
  IEMOCAP:
    preprocessed_dir: "Preprocessed"
    emotions: ["angry", "scare", "neutral", "sad", "surprise", "happy"]
dataloader:
  batch_size: 16
  num_workers: 0
models:
  pretrained_alexnet: "https://download.pytorch.org/models/alexnet-owt-4df8aa71.pth"
  save_location: "saved_models"
plots:
  save_location: "pictures"
